<script setup lang="ts">
import { ref } from 'vue'

const sections = ref([
  {
    title: 'What is D&D NPC AI?',
    content: 'D&D NPC AI is an advanced tool designed to help Dungeon Masters create rich, detailed Non-Player Characters (NPCs) for their Dungeons & Dragons campaigns. Our AI-powered generator takes into account various factors such as class, race, background, and purpose to craft unique and compelling characters that seamlessly fit into your world.'
  },
  {
    title: 'How It Works',
    content: 'Our system uses state-of-the-art natural language processing and machine learning algorithms to generate NPCs. By analyzing vast amounts of D&D lore, character archetypes, and storytelling patterns, our AI creates characters that are not only diverse but also consistent with the rich tapestry of the D&D universe.'
  },
  {
    title: 'Benefits for DMs',
    content: 'With D&D NPC AI, Dungeon Masters can save time on character creation, focus more on storytelling, and surprise their players with unique and memorable NPCs. Our tool helps maintain consistency across your campaign, ensures that each NPC has a rich background, and can even suggest potential plot hooks based on the generated characters.'
  },
  {
    title: 'Continuous Improvement',
    content: 'We\'re constantly updating our AI models with new data and improving our algorithms. This means that the NPCs generated by our system will continue to evolve and improve over time, providing you with an ever-expanding roster of characters to populate your campaigns.'
  }
])
</script>

<template>
  <div class="learn-more">
    <div class="container">
      <h1 class="page-title">Learn More About D&D NPC AI</h1>
      <div v-for="section in sections" :key="section.title" class="info-section">
        <h2>{{ section.title }}</h2>
        <p>{{ section.content }}</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.learn-more {
  padding: 6rem 0;
  background-color: var(--background-color);
}

.page-title {
  font-size: 3rem;
  color: var(--primary-color);
  margin-bottom: 2rem;
  text-align: center;
}

.info-section {
  margin-bottom: 3rem;
}

.info-section h2 {
  font-size: 2rem;
  color: var(--accent-color);
  margin-bottom: 1rem;
}

.info-section p {
  font-size: 1.1rem;
  line-height: 1.6;
}
</style>